server:
  port: 9090

#openrouteservice:
#  api-key: ${OPENROUTESERVICE_API_KEY}
#  base-url: https://api.openrouteservice.org

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:vanroute_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  jwt:
    expiration: ${JWT_EXPIRATION:900000}
    key: ${JWT_KEY:4QcYHiOKv6R1GIost25MwdDJNLayEubr3kj9nW8AxZqSFX0gfmhUTepCBPlV7z}
  
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100