server:
  port: 9090

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/pi
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true #mudar para true quando começar as migrations.