spring.profiles.active=local    

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${SENDER_EMAIL}
spring.mail.password=${SENDER_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=felipeacfornazeiro@gmail.com
spring.mail.password=${PASSWORD_APP}

                                                                                                                        

# botar aql notação que tenta pegar primeiro uma variavel de ambiente e dps tenta esse local
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}